#!/usr/bin/env bash

checkEnvFile()
{
    ENVFILE="$1/.env"
    if test ! -f "$ENVFILE"; then
        echo "$ENVFILE não exists."
        cp $1/.env-sample $ENVFILE
    fi
}

initAllEnv()
{
  checkEnvFile "."
  checkEnvFile "./infra/api"
  checkEnvFile "./infra/web"
}

initAllEnv

case $1 in
  "start")
    docker-compose up -d --no-deps
    ;;
  "test") docker-compose run api bash -c "npm install && npm install tape -g && npm run test";;
  "populate") docker-compose run api bash -c "npm install && npm run populate";;
  "prod") docker-compose up webserver_api ;;
  "stop") docker-compose down;;
esac
