#!/usr/bin/env bash

checkEnvFile()
{
    ENVFILE="$1/.env"
    if test ! -f "$ENVFILE"; then
        echo "$ENVFILE não exists."
        cp $1/.env-sample $ENVFILE
    fi
}

initAllEnv()
{
  checkEnvFile "."
  checkEnvFile "./infra/api"
  checkEnvFile "./infra/web"
}

case $1 in
  "install")
    initAllEnv
    docker-compose run api bash -c "npm install"
    docker-compose run web bash -c "npm install"
    ;;
  "start")
    docker-compose up -d
    ;;
  "test") docker-compose run api bash -c "npm install && npm install tape -g && npm run test";;
  "seeding")
    echo "Starting"
    docker-compose run api bash -c "npm install && npm run seeding";;
  "prod") docker-compose up webserver_api ;;
  "stop") docker-compose down;;
esac
